Resources:
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "my-iam-user"
      Policies:
        - PolicyName: "MyPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                Resource:
                  - "arn:aws:s3:::my-bucket"
                  - "arn:aws:s3:::my-bucket/*"
